language: java

cache:
  directories:
    - $HOME/.gradle/wrapper/

script: ./gradlew check -i
deploy:
  on:
    tags: true
    condition: "$TRAVIS_SECURE_ENV_VARS"
  provider: script
  script: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
